### ISSUE TITLE
Add a bundle import

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin#37]
Similarly to `vaadin-core/vaadin-core.html` import, we should have a `vaadin/vaadin.html` import which imports all the components in the package.

**Comment by Artur-** [comment]
Does this work correctly with bundling or do all the components end up in the minified bundle?

**Comment by jouni** [comment]
I would expect all the components to end up in the bundle.

I’m generally against these “all the things” imports (we should document somehow what the consequence for using these imports is), but since the vaadin-core package has it, I thought we should align here.

**Comment by web-padawan** [comment]
Fixed by #50
