### ISSUE TITLE
Clarify the free vs pro components

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin#39]
From time to time, users are asking us about free and pro parts of our offering.

Question: https://github.com/vaadin/vaadin-login/pull/50#issuecomment-447257475

>  How are make-it-free decisions made? Are there specific criteria for a component to meet, or random chance during team discussion, or...

Answer: https://github.com/vaadin/vaadin-login/pull/50#issuecomment-447306013

> It is more of a case-by-case matter (... and some details about the specific case)

This is probably not what the users actually expect. It would be nice to have a clear strategy documented on the website and linked from each of the PRO component repositories.

**Comment by jouni** [comment]
For the record: we’ve been trying hard, for a long time already, to come up with a decent strategy to help make these decisions. So far we haven’t really found anything that would apply to all cases without making someone cringe.

That said, we could still outline some basic principles that we think guide our decisions, but add a disclaimer that they are just guidelines and exceptions are likely to happen.

Also, we’re pretty “green“ with this topic, and the current phase is a bit of a “trial-by-fire” situation, that we don’t really know what works and what doesn’t. We’re listening for feedback about this constantly.

**Comment by jouni** [comment]
Where would you expect to find this kind of info?

**Comment by web-padawan** [comment]
I feel like there should be a page at https://vaadin.com/components explaining this.
Also, it would be nice to have a link to readme for each PRO component.

Let's remember the transparency and "saying things as they are" while figuring out a proper way to communicate this to our users, so that we get positive feedback eventually.

**Comment by web-padawan** [comment]
Closing, let's reopen if we gain some feedback regarding this topic.
