### ISSUE TITLE
[Feature Request] Autocomplete for imported web components

### ISSUE THREAD

**Issue by BBKolton** [vaadin/vaadin#51]
It would be extremely nice to get an IDE auto complete supported for the packaged web components on the npm repo. When I import the `@vaadin/vaadin`, I don't get any support at least in VS Code. Such things as showing the properties inside of the `@vaadin/vaadin-progress-bar` would be fantastic so I didn't have to go check the docs every time. 

Sorry if this isn't the right place, feel free to point me elsewhere!

**Comment by brion-fuller** [comment]
+1 for types definition on components.  Is there a roadmap for this?  It would be great to see what is available in the IDE.

**Comment by web-padawan** [comment]
Closing in favor of vaadin/vaadin-core#186
