### ISSUE TITLE
Collaborative components

### ISSUE THREAD

**Issue by juhopiirainen** [vaadin/vaadin#53]
Commenting / Activity log experience

Team communication capabilities like TaskMob can be added to your app with off the shelf components

**Comment by web-padawan** [comment]
There is a Polymer 2 component implementing comment list:
https://github.com/Hostabee/hostabee-comment-flow

Note: please don't be confused as `-flow` here is not related to Flow 😄

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/platform/issues/1838
