### ISSUE TITLE
Issue with wrapping Vaadin Controls using Angular Directives

### ISSUE THREAD

**Issue by msbasanth** [vaadin/vaadin#62]
Hi,

We are trying to create Angular wrapper for Vaadin WebComponents using Angular directives.

Why we are doing this?
*  Type checking in templates can happen at compile time
*  Can avoid CUSTOM_ELEMENTS_SCHEMA usage 
*  Can think the possibility of providing test harness specific to component in Angular

What we did ?
1) We wrapped Vaadin-Checkbox by extending it. We are yet to delegate properties, events etc.
```
import { Component, NgZone } from '@angular/core';
import {CheckboxElement} from '@vaadin/vaadin-checkbox/src/vaadin-checkbox.js'
import { ChangeDetectorRef, ElementRef } from '@angular/core';
import '@vaadin/vaadin-checkbox';

@Component({
  selector: 'vaadin-checkbox',
  template: '<ng-content></ng-content>',
})
export class CheckboxComponent extends CheckboxElement {
  protected el: HTMLElement;

  constructor(c: ChangeDetectorRef, r: ElementRef, protected z: NgZone) {
    super(c, r, z); // Here we tried super(); also
    c.detach();
    this.el = r.nativeElement;
  }
}
```

2) We created a new Angular app and used the vaadin-checkbox directive in the app.component.html

```
<vaadin-checkbox >Ok</vaadin-checkbox>
```

3) We are seeing the vaadin-checkbox rendered but an error observed.
![image](https://user-images.githubusercontent.com/17777813/73523631-4a5e4600-4431-11ea-8559-6ffc02de3040.png)

```
core.js:5809 ERROR TypeError: Illegal constructor
    at new PropertiesChanged (properties-changed.js:166)
    at new PropertyAccessors (property-accessors.js:115)
    at new TemplateStamp (template-stamp.js:171)
    at new PropertyEffects (property-effects.js:1107)
    at new PropertiesMixin (properties-mixin.js:113)
    at new PolymerElement (element-mixin.js:522)
    at new GestureEventListeners (gesture-event-listeners.js:38)
    at new VaadinThemePropertyMixin (vaadin-theme-property-mixin.js:4)
    at new VaadinThemableMixin (vaadin-themable-mixin.js:8)
    at new VaadinTabIndexMixin (vaadin-control-state-mixin.js:11)
```

We tried passing super() and with arguments but still getting this illegal constructor. 

Could you please suggest how we can extend Vaadin control at Angular side?

Regards
Basanth

**Comment by web-padawan** [comment]
Hi, looks like this might be related to transpiling `node_modules` to ES5.

Check out [origami](https://github.com/hotforfeature/origami#prepare-dependencies-es5-only) which helps to prepare Polymer components for using in Angular 7+.

**Comment by tomivirkki** [comment]
Adding the following in `package.json` "scripts" might also help (haven't tested with Angular)
```
"postinstall": "npm run prepare:es5",
"prepare:es5": "babel node_modules/@vaadin node_modules/@polymer node_modules/@webcomponents/shadycss -x '.js' --out-dir ./ --relative --presets @babel/env"
```

**Comment by msbasanth** [comment]
Thanks @web-padawan  and @tomivirkki 

We will look into origami, meanwhile we tried preparing with es5 and we are getting a different error.

```
zone.js:396 ERROR TypeError: Class constructor GestureEventListeners cannot be invoked without 'new'
    at CheckboxComponent.VaadinThemePropertyMixin [as constructor] (vaadin-theme-property-mixin.js:8)
    at CheckboxComponent.VaadinThemableMixin [as constructor] (vaadin-themable-mixin.js:11)
    at CheckboxComponent.VaadinTabIndexMixin [as constructor] (vaadin-control-state-mixin.js:15)
    at CheckboxComponent.VaadinControlStateMixin [as constructor] (vaadin-control-state-mixin.js:52)
    at CheckboxComponent.VaadinDirMixin [as constructor] (vaadin-dir-mixin.js:31)
    at CheckboxComponent.VaadinElementMixin [as constructor] (vaadin-element-mixin.js:29)
    at CheckboxComponent.CheckboxElement [as constructor] (vaadin-checkbox.js:55)
    at new CheckboxComponent(alert.component.ts:17)
    at NodeInjectorFactory.CheckboxComponent[as factory] (alert.component.ts:20)
    at getNodeInjectable (core.js:3666)
```
Then we got to know that extending from CheckboxElement is not really required as ElementRef.nativeElement already contain vaadin-checkbox. So now we don't have constructor errors after removing VaadinCheckbox extension.

```
@Component({
  selector: 'vaadin-checkbox',
  template: '<ng-content></ng-content>'
})
export class VaadinComponent {
  protected el: HTMLElement;
  constructor(c: ChangeDetectorRef, r: ElementRef, protected z: NgZone) {
    this.el = new  CheckboxElement(); // Without new CheckboxElement we are not seeing WebComponent rendered
    c.detach();
    this.el = r.nativeElement;
  }
}
```
So we removed extending from CheckBoxElement and now with the above code we are able to see the WebComponent rendered. 

**Observation**
1. With _new  CheckboxElement()_ the WebComponent is rendered.
2. If you have _window.customElements.define("vaadin-checkbox", CheckboxElement);_ instead of new VaadinCheckbox still WebComponent is rendered.

So it looks like **customElement registration is not happening** if we only use ElementRef instance.

How we can trigger customElement registration without creating an instance or explicitly registering to the custom element? Or any other approach which is more suitable for wrapping WebComponents in Angular?

Regards
Basanth

**Comment by tomivirkki** [comment]
Since you're transpiling to es5, you'll also need to include this https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs#custom-elements-es5-adapterjs

**Comment by msbasanth** [comment]
Thanks for the quick reply.

This is my **index.html snippet**
```
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.1.3/custom-elements-es5-adapter.js"></script>
```

My polyfills.ts

```
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'; 

import '@webcomponents/custom-elements/src/native-shim';
import '@webcomponents/custom-elements/custom-elements.min';
```

I tried adding both ways so app is getting custom-elements-es5-adapter.js, but the error still persists. 

Now we are checking whether we can avoid limiting our WebComponents to ES5 as in the below code.

```
@Component({
  selector: 'vaadin-checkbox',
  template: '<ng-content></ng-content>'
})
export class VaadinComponent {
  protected el: HTMLElement;
  constructor(c: ChangeDetectorRef, r: ElementRef, protected z: NgZone) {
    this.el = new  CheckboxElement(); // Without new CheckboxElement we are not seeing WebComponent rendered
    c.detach();
    this.el = r.nativeElement;
  }
}
```
Any comment on, how we can trigger customElement registration without creating an instance here?

Regards
Basanth

**Comment by web-padawan** [comment]
These two scripts are doing exactly the same so you only need one of them:

```
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'; 
import '@webcomponents/custom-elements/src/native-shim';
```

Also, you **only** need them with latest browsers (not in older ones like IE11).
You should not need calling `new CheckboxElement()` manually.

Could you provide is with a small reproduction so we could investigate?

**Comment by tomivirkki** [comment]
Also see if you can find something useful from this repo/branch https://github.com/vaadin/base-starter-angular/tree/examples

**Comment by msbasanth** [comment]
> These two scripts are doing exactly the same so you only need one of them:
> 
> ```
> import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js'; 
> import '@webcomponents/custom-elements/src/native-shim';
> ```
> 
> Also, you **only** need them with latest browsers (not in older ones like IE11).
> You should not need calling `new CheckboxElement()` manually.
> 
> Could you provide is with a small reproduction so we could investigate?

**Comment by msbasanth** [comment]
Hi @web-padawan & @tomivirkki,

Here is the GitHub sample where we are trying _vaadin-checkbox_ wrapping in an AngularComponent using Angular directives. https://github.com/msbasanth/vaadin-ng-wrapper

As you could see we have _new  CheckboxElement();_ in https://github.com/msbasanth/vaadin-ng-wrapper/blob/master/src/app/vaddin-checkbox-component/vaddin-checkbox-component.ts

Which is only needed for registering the custom element(?).  It looks like the custom element registration is not happening when we trigger vaadin-checxbox creation through an Angular directive.

Any further inputs are appreciated.

Regards
Basanth

**Comment by web-padawan** [comment]
@msbasanth I have tried your example locally and updated it to only use this import:
```js
import '@vaadin/vaadin-checkbox/vaadin-checkbox.js';
```

Importing this file is enough for `vaadin-checkbox` custom element to be defined.
Note that is also imports the component definition from `src` internally.

Speaking about extending HTML element and registering that as Angular element, personally I'm not sure whether that is possible. At least I haven't seen the example of such usage.

**Comment by msbasanth** [comment]
Hi,

Thanks for the update.

Regarding extending vaadin-checkbox element: We are trying an approach similar to @ionic/angular -  https://github.com/ionic-team/ionic/tree/master/angular

Most of our applications are in Angular and would like to give a wrapper without adding a new node in between. Which gives benefits like,
- Type checking in templates can happen at compile time
- Can avoid CUSTOM_ELEMENTS_SCHEMA usage
- Can think the possibility of providing test harness specific to component in Angular
- We can have control over change detection strategy in Angular

With _"new CheckboxElement()"_ the wrapping works and vaadin-checkbox rendered properly. One thing which is confusing us, the (one time) custom element registration is not happening without "_new CheckboxElement_". Registering custom element from Anglar wrapper (_window.customElements.define("vaadin-checkbox", CheckboxElement)_) also works but it is not a cleaner approach.

NB: We are not converting vaadin-checkbox to Angular Element we just do an angular wrapping of vaadin element.

Regards
Basanth

**Comment by web-padawan** [comment]
Ok, now I finally understand what you are trying to achieve, thanks for the clarification.

However as I mentioned above, I changed the import and it worked for me locally.

Note, It's generally better to use import to the actual file:
```js
import '@vaadin/vaadin-checkbox/vaadin-checkbox.js';
```

Instead of the one that is included to your example
```js
import '@vaadin/vaadin-checkbox';
```

Please let me know if this still doesn't work for you.

**Comment by msbasanth** [comment]
It worked. Thanks a lot @web-padawan
