### ISSUE TITLE
Vaadin website - "Customer stories" redirects to "/directory"

### ISSUE THREAD

**Issue by NgyAnthony** [vaadin/vaadin#65]
Hi,

I found a mistake on your website, it seems that "Customer stories" redirects to "/directory" instead of "/customer-stories".
Same issue on my phone so I don't think it's an issue on my side.

<img width="798" alt="Capture d’écran 2020-04-01 à 20 46 59" src="https://user-images.githubusercontent.com/26002874/78175020-85452000-745a-11ea-9d25-c666be1297e8.png">
<img width="614" alt="Capture d’écran 2020-04-01 à 20 47 03" src="https://user-images.githubusercontent.com/26002874/78175025-86764d00-745a-11ea-8691-1b724019d410.png">

**Comment by web-padawan** [comment]
Thanks for the issue! Will forward it to the team.

**Comment by NgyAnthony** [comment]
Issue seems to be fixed, I'm closing the issue.
