### ISSUE TITLE
Height-by-rows bug with drag and drop

### ISSUE THREAD

**Issue by mattheol** [vaadin/vaadin#72]
Issue with grid when height-by-rows is enabled.
Scroll is blinking and cannot drop dragged item below last item.
Workaround is to add footer, but it's impossible to change height of it.
![image](https://user-images.githubusercontent.com/38963051/90342317-8a6ccb00-e007-11ea-8ae3-aa046111a721.png)

**Comment by tomivirkki** [comment]
Closing as a duplicate of https://github.com/vaadin/vaadin-grid-flow/issues/830
