### ISSUE TITLE
Register the namespace "vaadin"

### ISSUE THREAD

**Issue by nuxodin** [vaadin/vaadin#77]
Hi
Maybe you want to register the namespace "vaadin" here with a pull request?
https://github.com/nuxodin/web-namespace-registry

**Comment by web-padawan** [comment]
Hi, to me it's unclear what's the point of your project and why do we register the namespace there.
Are you planning some build some tools around it, or is it just a collection of projects?

**Comment by nuxodin** [comment]
Hi
The point is that if others are planning to develop a webcomponents framework, they can look to see if there might be a conflict with another framework.
Sure, "vaadin" is not very prone to a conflict, but who knows...

**Comment by web-padawan** [comment]
We never had this problem with a namespace. In practice, people were asking about why we don't use a shorter namespace like `v-grid` and not `vaadin-grid`. One of the reasons behind this was to make sure our components are unique.

I'm closing this issue for now but will keep an eye on your project to see how it evolves.
